version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.11-slim-bookworm"
    volumes:
      - ../:/workspaces/app/:cached
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: sleep infinity
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge
